/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as PesananRouteImport } from './routes/pesanan'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminKatalogRouteImport } from './routes/admin.katalog'
import { Route as AdminPengaturanRouteImport } from './routes/admin.pengaturan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananRoute = PesananRouteImport.update({
  id: '/pesanan',
  path: '/pesanan',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKatalogRoute = AdminKatalogRouteImport.update({
  id: '/admin/katalog',
  path: '/admin/katalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPengaturanRoute = AdminPengaturanRouteImport.update({
  id: '/admin/pengaturan',
  path: '/admin/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/pesanan': typeof PesananRoute
  '/admin/katalog': typeof AdminKatalogRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/pesanan': typeof PesananRoute
  '/admin/katalog': typeof AdminKatalogRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/pesanan': typeof PesananRoute
  '/admin/katalog': typeof AdminKatalogRoute
  '/admin/pengaturan': typeof AdminPengaturanRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/pesanan'
    | '/admin/katalog'
    | '/admin/pengaturan'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/pesanan'
    | '/admin/katalog'
    | '/admin/pengaturan'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/checkout'
    | '/pesanan'
    | '/admin/katalog'
    | '/admin/pengaturan'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  PesananRoute: typeof PesananRoute
  AdminKatalogRoute: typeof AdminKatalogRoute
  AdminPengaturanRoute: typeof AdminPengaturanRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan': {
      id: '/pesanan'
      path: '/pesanan'
      fullPath: '/pesanan'
      preLoaderRoute: typeof PesananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/katalog': {
      id: '/admin/katalog'
      path: '/admin/katalog'
      fullPath: '/admin/katalog'
      preLoaderRoute: typeof AdminKatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pengaturan': {
      id: '/admin/pengaturan'
      path: '/admin/pengaturan'
      fullPath: '/admin/pengaturan'
      preLoaderRoute: typeof AdminPengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  PesananRoute: PesananRoute,
  AdminKatalogRoute: AdminKatalogRoute,
  AdminPengaturanRoute: AdminPengaturanRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
